### ISSUE TITLE
Feature: User can search for airports

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/ajax-project#1]
## 💰 Motivation

Pilots need to obtain airport weather and charts before flying.

## 📐 Plan

Create a form that allows users to search for an airport.

## 🖼️ Wireframes

![Screen Shot 2022-11-14 at 2 41 39 PM](https://user-images.githubusercontent.com/111034849/201783337-863c282d-bfd9-487d-b73e-0fb9d7f17179.png)
![Screen Shot 2022-11-14 at 2 41 26 PM](https://user-images.githubusercontent.com/111034849/201783339-40b3c611-e701-4091-a8c4-02ae9bfdab17.png)

## ✅ Task List

- [x] Add a `div` to the HTML.
- [x] Add a form for searching for an airport to the `div`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the journal entry form `required`.
- [x] Listen for `'submit'` events on the airport form and:
  - [x] Put the form's input values into a new object.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the form inputs.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

**Comment by parkersiu** [comment]
Completed
