### ISSUE TITLE
Feature: User can view airport weather and charts

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/ajax-project#2]
## 💰 Motivation

Once a user searches for an airport, they will want to see weather and charts.

## 📐 Plan

Display the airport's current weather and a link to the airport diagram.

## 🖼️ Wireframes

![Screen Shot 2022-11-14 at 2 33 11 PM](https://user-images.githubusercontent.com/111034849/201782119-83e9fea9-1cd9-4465-afc9-9eee7f153ab6.png)
![Screen Shot 2022-11-14 at 2 33 05 PM](https://user-images.githubusercontent.com/111034849/201782122-b99a6ea9-fad1-44e7-83f5-198d507ded14.png)

## ✅ Task List

- [x] Add a sibling `div[data-view="airport"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="airport"]` element in the HTML.
- [x] Add some dummy weather info to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the airport info list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single airport `entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Remove the example HTML entries once the airport info is successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Search.
- [x] Add an anchor to the airport view that shows the search form.
- [x] Ensure that submitting a new airport search also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new airport search automatically shows the `'airport'` view without reloading the page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
