### ISSUE TITLE
Feature: User can add airports to favorites list

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/ajax-project#3]
## 💰 Motivation

Users will want to be able to save a list of their favorite airports.

## 📐 Plan

Allow users to click a favorites button that adds the airport to their favorites list.

## 🖼️ Wireframes

![Screen Shot 2022-11-14 at 2 33 11 PM](https://user-images.githubusercontent.com/111034849/201784275-806b0c78-7845-4007-adc6-af8d5e888c85.png)
![Screen Shot 2022-11-14 at 2 33 05 PM](https://user-images.githubusercontent.com/111034849/201784277-246104c1-16fd-4743-9cc6-7d4de64012f7.png)

## ✅ Task List

- [x] Add a star icon to the airport view.
- [x] When clicked, the star should display a solid color.
- [x] When clicked, save the airport id to the data model.
- [x] If the airport is already on the favorites list, display the star icon as solid.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
