### ISSUE TITLE
Feature: User can view their favorites list

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/ajax-project#4]
## 💰 Motivation

Users will want to view their favorites list.

## 📐 Plan

Display the user's favorite airports in the order they were added.

## 🖼️ Wireframes

![Screen Shot 2022-11-14 at 2 43 36 PM](https://user-images.githubusercontent.com/111034849/201784473-6bec8c83-e09b-45c1-8caa-d293bd4653c9.png)
![Screen Shot 2022-11-14 at 2 43 42 PM](https://user-images.githubusercontent.com/111034849/201784475-7506909b-2b4e-40ad-9580-ac9d1baf0878.png)

## ✅ Task List

- [x] Add a sibling `div[data-view="favorites"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="favorites"]` element in the HTML.
- [x] Add some dummy favorites to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the favorites list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single `airport` object and returns a DOM tree that matches one of the example favorites in the HTML.
- [x] Use a loop to create a DOM tree for each favorite airport in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML favorites list once the user's favorite airports are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Favorites.
- [x] Add an anchor to the favorites view that shows the favorites view.
- [x] Ensure that clicking go displays the correct airport view page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
