### ISSUE TITLE
Feature: User can delete favorites

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/ajax-project#5]
## 💰 Motivation

If a user decides that they no longer wish to keep a favorite airport, they should be able to delete it.

## 📐 Plan

Allow users to delete an airport from the favorites screen.

## 🖼️ Wireframes

![Screen Shot 2022-11-14 at 2 57 04 PM](https://user-images.githubusercontent.com/111034849/201785407-8f17aeb0-5793-4d4e-84a4-0883817f93fd.png)
![Screen Shot 2022-11-14 at 2 56 57 PM](https://user-images.githubusercontent.com/111034849/201785410-3ddfa78f-202b-493b-8c97-91b204e60560.png)

## ✅ Task List

- [x] Add an icon for deleting an airport to the favorites view.
- [x] Show a confirmation modal when the user clicks the delete icon.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the airport from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the Favorites list if the user clicks Delete.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
